# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lncli < Formula
  desc "LearnHub CLI — initialize and verify hands-on coding projects"
  homepage "https://github.com/adityasunny1189/lncli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4d2bd75dc600bcc339f4d518895c40538f499211949c19b722f6ee3de5192e3c"

      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_darwin_arm64.tar.gz"
      sha256 "329ddfe02ac95e56a0ff5ca5f9fa2b3117c88ccfcca90a80a3c3cf3cc2baa770"

      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_linux_amd64.tar.gz"
      sha256 "7095ef50aa6b50841b9767b669a1e4d543bb472a60cb49ae9ce549fb02fe5815"
      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_linux_arm64.tar.gz"
      sha256 "5bc17fdab0657074dd93173fc977a7c5b00a023502965688d3aafc6bd419e6bd"
      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  test do
    system "#{bin}/lncli", "version"
  end
end
