# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lncli < Formula
  desc "LearnHub CLI — initialize and verify hands-on coding projects"
  homepage "https://github.com/adityasunny1189/lncli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.3.0/lncli_0.3.0_darwin_amd64.tar.gz"
      sha256 "1e0cb87979e232cb2bf2f7d2c75cd6cb5f756a2e3faa26569509949ef8398481"

      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.3.0/lncli_0.3.0_darwin_arm64.tar.gz"
      sha256 "8d1ad8247995d3ec7ade232e565ab6c03076d43e6a29c7352e5c599fed3545a7"

      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.3.0/lncli_0.3.0_linux_amd64.tar.gz"
      sha256 "7bb42f3a901c356496ecb2e4d380b3c3b4461f257c3bbf0cab18ff09978fe091"
      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.3.0/lncli_0.3.0_linux_arm64.tar.gz"
      sha256 "349c10e862a3d83e44ea8a990d7815e7d8ad7fcf064c16d073619383f303d598"
      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  test do
    system "#{bin}/lncli", "version"
  end
end
