# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lncli < Formula
  desc "LearnHub CLI — initialize and verify hands-on coding projects"
  homepage "https://github.com/adityasunny1189/lncli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_darwin_amd64.tar.gz"
      sha256 "7400ce59f7513a8be417926f08f7f97ae5d2ebafa3a71fa6117e9834698cd81e"

      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7dc9c306737912e0d210ad1d7ae5e58b6849594be13b1dea272fb4fd85b65cb7"

      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_linux_amd64.tar.gz"
      sha256 "8f8d3ac384220a399868878354d9da41449e8380997259da98241179b7cf788b"
      define_method(:install) do
        bin.install "lncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adityasunny1189/lncli/releases/download/v0.1.0/lncli_0.1.0_linux_arm64.tar.gz"
      sha256 "0225d3c035396751b6ce1fd5d2c669b00e184e356cf8e99e17f65d2d851fe81d"
      define_method(:install) do
        bin.install "lncli"
      end
    end
  end

  test do
    system "#{bin}/lncli", "version"
  end
end
